<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TRUUGQA03" name="USSD.J_Buy_Goods" tests="7" failures="1" timestamp="2021-02-10T08:58:00 EAT" time="83.574" errors="0">
  <testcase name="Check_if_system_shows_error_when_using_amount_less_than_kes_50_Postpaid_amount" time="38.903" classname="USSD.J_Buy_Goods">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at USSD.J_Buy_Goods.Check_if_system_shows_error_when_using_amount_less_than_kes_50_Postpaid_amount(J_Buy_Goods.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Check_if_system_shows_error_when_using_amount_less_than_kes_50_Postpaid_amount -->
  <system-out/>
  <testcase name="Check_if_system_shows_error_when_using_amount_More_than_kes_200000_Daily_limit_Postpaid_amount" time="36.312" classname="USSD.J_Buy_Goods"/>
  <system-out/>
  <testcase name="Check_if_system_shows_error_when_using_amount_More_than_kes_70000_Postpaid_amount" time="1.798" classname="USSD.J_Buy_Goods"/>
  <system-out/>
  <testcase name="Check_if_system_shows_error_when_using_invalid_data_invalid_account_number" time="1.635" classname="USSD.J_Buy_Goods"/>
  <system-out/>
  <testcase name="Check_if_system_shows_error_when_using_invalid_data_invalid_postpaid_account_number" time="1.485" classname="USSD.J_Buy_Goods"/>
  <system-out/>
  <testcase name="Verify_correct_charges_on_successful_electricity_postpaid_bill" time="1.947" classname="USSD.J_Buy_Goods"/>
  <system-out/>
  <testcase name="Verify_that_customers_debit_account_is_correctly_narrated" time="1.494" classname="USSD.J_Buy_Goods"/>
  <system-out/>
</testsuite> <!-- USSD.J_Buy_Goods -->
