<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TRUUGQA03" name="USSD.C_Fund_Transfer_Account_to_Mobile_Money" tests="13" failures="2" timestamp="2021-03-11T09:41:55 EAT" time="24.467" errors="0">
  <testcase name="Transfer_to_mpesa_Test_cases" time="0.132" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money"/>
  <system-out/>
  <testcase name="Verify_that_customer_can_access_send_money_to_mpesa_menu_on_USSD" time="7.974" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money"/>
  <system-out/>
  <testcase name="Verify_that_customer_can_selected_To_Mobile_money_on_USSD" time="6.051" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money"/>
  <system-out/>
  <testcase name="Verify_that_customer_can_selected_To_my_number_on_USSD" time="0.942" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money"/>
  <system-out/>
  <testcase name="Verify_that_customer_can_selected_To_other_number_on_USSD" time="0.981" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money"/>
  <system-out/>
  <testcase name="Verify_that_customer_can_enter_the_amount_to_send_on_USSD" time="1.139" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money"/>
  <system-out/>
  <testcase name="Verify_customer_cannot_send_money_to_Mpesa_below_the_Maximum_amount_allowed" time="1.108" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at USSD.C_Fund_Transfer_Account_to_Mobile_Money.Verify_customer_cannot_send_money_to_Mpesa_below_the_Maximum_amount_allowed(C_Fund_Transfer_Account_to_Mobile_Money.java:351)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_customer_cannot_send_money_to_Mpesa_below_the_Maximum_amount_allowed -->
  <system-out/>
  <testcase name="Verify_customer_cannot_send_money_to_Mpesa_above_the_Minimum_amount_allowed" time="1.216" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at USSD.C_Fund_Transfer_Account_to_Mobile_Money.Verify_customer_cannot_send_money_to_Mpesa_above_the_Minimum_amount_allowed(C_Fund_Transfer_Account_to_Mobile_Money.java:397)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_customer_cannot_send_money_to_Mpesa_above_the_Minimum_amount_allowed -->
  <system-out/>
  <testcase name="Verify_that_the_System_generates_an_error_mesasge_where_the_customer_has_provided_an_Invalid_amount_as_the_Transfer_Amount" time="1.273" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money"/>
  <system-out/>
  <testcase name="Verify_that_the_System_generates_an_error_mesasge_where_the_customer_has_provided_an_Invalid_mobile_number" time="1.083" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money"/>
  <system-out/>
  <testcase name="Verify_that_Customer_Can_Proceed_and_confirm_successfully_send_amount_to_Mpesa_my_number" time="1.336" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money"/>
  <system-out/>
  <testcase name="Verify_that_Customer_Can_Proceed_and_confirm_successfully_send_amount_to_Mpesa_other_number" time="1.228" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money"/>
  <system-out/>
  <testcase name="End_transfer_to_mpesa_Test_cases" time="0.004" classname="USSD.C_Fund_Transfer_Account_to_Mobile_Money"/>
  <system-out/>
</testsuite> <!-- USSD.C_Fund_Transfer_Account_to_Mobile_Money -->
